#!/usr/bin/env python3

# Agent to go back & forth along a line, visualising the observations at each
# step

from benchbot_api import BenchBot
from line_agent import LineAgent

if __name__ == '__main__':
    BenchBot(agent=LineAgent()).run()
