#!/usr/bin/env python

# Agent to go back & forth along a line, visualising the observations at each
# step

from benchbot_api.benchbot import BenchBot

from interactive_agent import InteractiveAgent

bb = BenchBot()
a = InteractiveAgent()

observations = bb.reset()
result = None
while not a.is_done():
    action, action_args = a.pick_action(observations)
    observations, reward, info = bb.step(action, **action_args)
bb.finish(result)
