#!/usr/bin/env python3

# Demo agent for passive mode that steps through each of the available poses in
# the environment, executing the "move_next" action recursively. Observations
# are visualised by the agent at the completion of each action.

from benchbot_api import BenchBot
from guided_agent import GuidedAgent

if __name__ == '__main__':
    BenchBot(agent=GuidedAgent()).run()
