#!/usr/bin/env python

# Demo agent for passive mode that steps through each of the available poses in
# the environment, executing the "move_next" action recursively. Observations
# are visualised by the agent at the completion of each action.

from benchbot_api.benchbot import BenchBot

from guided_agent import GuidedAgent

bb = BenchBot()
a = GuidedAgent()

observations = bb.reset()
result = None
while not a.is_done():
    action, action_args = a.pick_action(observations)
    observations, reward, info = bb.step(action, **action_args)
bb.finish(result)
